import json
from typing import Any


def compact_json(value: Any) -> str:
    """Serialize JSON compactly for LLM prompts."""
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
    )

def architecture_core(value: Any) -> dict:
    """
    Return only the core architecture fields generated by
    the Architecture Agent.

    Downstream agents should use this instead of serializing
    the entire accumulated architecture dictionary, because
    that dictionary also contains reports produced by later
    agents.
    """
    if not isinstance(value, dict):
        return {}

    keys = (
        "frontend",
        "backend",
        "database",
        "storage",
        "authentication",
        "networking",
        "compute",
        "monitoring",
        "security",
        "scalability",
    )

    return {
        key: value[key]
        for key in keys
        if key in value
    }
